version: 2.1

jobs:
  build-docker:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # Enabling this requires paid CircleCI plan
          version: 19.03.13
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/ansible-aws-cli:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/ansible-aws-cli:$TAG

workflows:
  build-and-deploy:
    jobs:
      - build-docker:
          context:
            - Docker
